from django.db import models


class SchSettings(models.Model):
    name = models.CharField(max_length=100, unique=True)
    biometric = models.BooleanField(default=0)
    biometric_device = models.TextField(null=True, blank=True)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    address = models.TextField(null=True)
    lang_id = models.IntegerField(blank=True, null=True)
    languages = models.CharField(max_length=500, blank=True, null=True)
    dise_code = models.CharField(
        max_length=50, unique=True, blank=True, null=True)
    date_format = models.CharField(max_length=50, blank=True, null=True)
    time_format = models.CharField(max_length=255, blank=True, null=True)
    currency = models.CharField(max_length=50, blank=True, null=True)
    currency_symbol = models.CharField(max_length=50, blank=True, null=True)
    is_rtl = models.CharField(default='disabled', max_length=50)
    is_duplicate_fees_invoice = models.IntegerField(default=0)
    timezone = models.CharField(default='UTC', max_length=30)
    session_id = models.IntegerField(blank=True, null=True)
    cron_secret_key = models.CharField(max_length=100, blank=True, null=True)
    # currency_place = models.CharField(max_length=100)
    # start_month = models.CharField(max_length=100)
    # attendence_type = models.CharField(max_length=100)
    # image = models.CharField(max_length=100)
    # admin_logo = models.CharField(max_length=100)
    # admin_small_logo = models.CharField(max_length=100)
    # theme = models.CharField(max_length=100)
    # fee_due_days = models.CharField(max_length=100)
    # adm_auto_insert = models.CharField(max_length=100)
    # adm_prefix = models.CharField(max_length=100)
    # adm_start_from = models.CharField(max_length=100)
    # adm_no_digit = models.CharField(max_length=100)
    # adm_update_status = models.CharField(max_length=100)
    # staffid_auto_insert = models.CharField(max_length=100)
    # staffid_prefix = models.CharField(max_length=100)
    # staffid_start_from = models.CharField(max_length=100)
    # staffid_no_digit = models.CharField(max_length=100)
    # staffid_update_status = models.CharField(max_length=100)
    # is_active = models.CharField(max_length=100)
    # online_admission = models.CharField(max_length=100)
    # is_blood_group = models.CharField(max_length=100)
    # is_student_house = models.CharField(max_length=100)
    # roll_no = models.CharField(max_length=100)
    # category = models.CharField(max_length=100)
    # religion = models.CharField(max_length=100)
    # cast = models.CharField(max_length=100)
    # mobile_no = models.CharField(max_length=100)
    # student_email = models.CharField(max_length=100)
    # admission_date = models.CharField(max_length=100)
    # lastname = models.CharField(max_length=100)
    # middlename = models.CharField(max_length=100)
    # student_photo = models.CharField(max_length=100)
    # student_height = models.CharField(max_length=100)
    # student_weight = models.CharField(max_length=100)
    # measurement_date = models.CharField(max_length=100)
    # father_name = models.CharField(max_length=100)
    # father_phone = models.CharField(max_length=100)
    # father_occupation = models.CharField(max_length=100)
    # father_pic = models.CharField(max_length=100)
    # mother_name = models.CharField(max_length=100)
    # mother_phone = models.CharField(max_length=100)
    # mother_occupation = models.CharField(max_length=100)
    # mother_pic = models.CharField(max_length=100)
    # guardian_name = models.CharField(max_length=100)
    # guardian_relation = models.CharField(max_length=100)
    # guardian_phone = models.CharField(max_length=100)
    # guardian_email = models.CharField(max_length=100)
    # guardian_pic = models.CharField(max_length=100)
    # guardian_occupation = models.CharField(max_length=100)
    # guardian_address = models.CharField(max_length=100)
    # current_address = models.CharField(max_length=100)
    # permanent_address = models.CharField(max_length=100)
    # route_list = models.CharField(max_length=100)
    # hostel_id = models.CharField(max_length=100)
    # bank_account_no = models.CharField(max_length=100)
    # ifsc_code = models.CharField(max_length=100)
    # bank_name = models.CharField(max_length=100)
    # national_identification_no = models.CharField(max_length=100)
    # local_identification_no = models.CharField(max_length=100)
    # rte = models.CharField(max_length=100)
    # previous_school_details = models.CharField(max_length=100)
    # student_note = models.CharField(max_length=100)
    # upload_documents = models.CharField(max_length=100)
    # staff_designation = models.CharField(max_length=100)
    # staff_department = models.CharField(max_length=100)
    # staff_last_name = models.CharField(max_length=100)
    # staff_father_name = models.CharField(max_length=100)
    # staff_mother_name = models.CharField(max_length=100)
    # staff_date_of_joining = models.CharField(max_length=100)
    # staff_phone = models.CharField(max_length=100)
    # staff_emergency_contact = models.CharField(max_length=100)
    # staff_marital_status = models.CharField(max_length=100)
    # staff_photo = models.CharField(max_length=100)
    # staff_permanent_address = models.CharField(max_length=100)
    # staff_qualification = models.CharField(max_length=100)
    # staff_work_experience = models.CharField(max_length=100)
    # staff_epf_no = models.CharField(max_length=100)
    # staff_note = models.CharField(max_length=100)
    # staff_basic_salary = models.CharField(max_length=100)
    # staff_contract_type = models.CharField(max_length=100)
    # staff_work_shift = models.CharField(max_length=100)
    # staff_work_location = models.CharField(max_length=100)
    # staff_leaves = models.CharField(max_length=100)
    # staff_account_details = models.CharField(max_length=100)
    # staff_social_media = models.CharField(max_length=100)
    # staff_upload_documents = models.CharField(max_length=100)
    # mobile_api_url = models.CharField(max_length=100)
    # app_primary_color_code = models.CharField(max_length=100)
    # app_secondary_color_code = models.CharField(max_length=100)
    # app_logo = models.CharField(max_length=100)
    # student_profile_edit = models.CharField(max_length=100)
    # start_week = models.CharField(max_length=100)
    # my_question = models.CharField(max_length=100)
    # created_at = models.DateTimeField(auto_add_now=True)
    # updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
