# Generated by Django 3.2.16 on 2023-06-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('reference', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateTimeField()),
                ('note', models.TextField()),
                ('source', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('assigned', models.CharField(max_length=100)),
                ('school_class', models.IntegerField()),
                ('no_of_child', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'enquiries',
            },
        ),
    ]
