# Generated by Django 3.2.16 on 2023-12-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('biometric', models.BooleanField(default=0)),
                ('biometric_device', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
