# Generated by Django 3.2.16 on 2024-01-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schsettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='cron_secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='currency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='date_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='dise_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='is_duplicate_fees_invoice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='is_rtl',
            field=models.CharField(default='disabled', max_length=50),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='lang_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='languages',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='session_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='time_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schsettings',
            name='timezone',
            field=models.CharField(default='UTC', max_length=30),
        ),
        migrations.AlterField(
            model_name='schsettings',
            name='biometric_device',
            field=models.TextField(blank=True, null=True),
        ),
    ]
