# Generated by Django 3.2.16 on 2024-01-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_settings', '0002_auto_20240103_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schsettings',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='schsettings',
            name='dise_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='schsettings',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
